name: armTemplateDeployment

on:
  push:
    branches:
      - main

  workflow_dispatch:

env:
  subscriptionId: 33665a07-097d-48db-b1f9-dc30012e19d6

jobs:
  armDeployStaging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    env:
      resource_group_name: rg-stg-githubactions
      location: westeurope
    environment:
      name: staging

    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Resource Group ${{ env.resource_group_name }}
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{ env.subscriptionId }}
          region: "${{ env.location }}"
          template: ./arm-templates/resourcegroup.json
          parameters:
            location="${{ env.location }}"
            resourceGroupName=${{ env.resource_group_name }}
          deploymentName: ${{ env.resource_group_name }}

      - name: Deploy Storage Account
        uses: Azure/arm-deploy@v1
        id: storageAccountDeploy
        with:
          scope: resourcegroup
          resourceGroupName: ${{ env.resource_group_name }}
          subscriptionId: ${{ env.subscriptionId }}
          template: ./arm-templates/storageaccount.json
          parameters: 
            sku=Standard_LRS
            storageAccountName=afuglobostg002
            location="${{ env.location }}"
          deploymentMode: incremental

      - name: Deploy Virtual machine
        uses: Azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourceGroupName: ${{ env.resource_group_name }}
          subscriptionId: ${{ env.subscriptionId }}
          template: ./arm-templates/virtualmachine.json
          parameters: 
            adminPassword=${{ secrets.UBUNTU_ADMIN_PASSWORD }}
            location="${{ env.location }}"
          deploymentMode: incremental

      - name: App Service Web App Build Action
        uses: Azure/appservice-build@v3
        with:
          app-name: node-rn
          publish-profile: ${{ secrets.azureWebAppPublishProfile }}



        

  armDeployProduction:
    name: Deploy to Production
    runs-on: ubuntu-latest
    env:
      resource_group_name: rg-prod-githubactions
      location: westeurope
    environment:
      name: production
      
    needs: armDeployStaging

    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Resource Group ${{ env.resource_group_name }}
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{ env.subscriptionId }}
          region: "${{ env.location }}"
          template: ./arm-templates/resourcegroup.json
          parameters:
            location="${{ env.location }}"
            resourceGroupName=${{ env.resource_group_name }}
          deploymentName: ${{ env.resource_group_name }}

      - name: Deploy Storage Account
        uses: Azure/arm-deploy@v1
        id: storageAccountDeploy
        with:
          scope: resourcegroup
          resourceGroupName: ${{ env.resource_group_name }}
          subscriptionId: ${{ env.subscriptionId }}
          template: ./arm-templates/storageaccount.json
          parameters: 
            sku=Standard_LRS
            storageAccountName=afuglobostg003
            location="${{ env.location }}"
          deploymentMode: incremental

      - name: Deploy Virtual machine
        uses: Azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourceGroupName: ${{ env.resource_group_name }}
          subscriptionId: ${{ env.subscriptionId }}
          template: ./arm-templates/virtualmachine.json
          parameters: 
            adminPassword=${{ secrets.UBUNTU_ADMIN_PASSWORD }}
            location="${{ env.location }}"
          deploymentMode: incremental