name: armTemplateDeployment
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  SUB_ID: ${{ secrets.SUBSCRIPTIONID}}
  AZURE_WEBAPP_NAME: "furi102-stg"   # Replace this with your Azure App Service name
  AZURE_WEBAPP_PACKAGE_PATH: '.'   # Replace this with the path to your Node.js app files, if it's not at the root of the repository

jobs:
  armDeployStaging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    env:
      resource_group_name: rg-stg-ghost
      location: westeurope
      hostingPlanName: furi102-stg-plan
    environment:
      name: staging
    steps:
      - uses: actions/checkout@v2
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy Resource Group ${{ env.resource_group_name }}
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{ env.SUB_ID }}
          region: "${{ env.location }}"
          template: ./arm-templates/resourcegroup.json
          parameters:
            location="${{ env.location }}"
            resourceGroupName=${{ env.resource_group_name }}
          deploymentName: ${{ env.resource_group_name }}
          
      - name: Deploy azure App service
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ env.SUB_ID }}
          resourceGroupName: ${{ env.resource_group_name }}
          template: ./arm-templates/stg-azuredeploy.json
          deploymentMode: complete
  armDeploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    env:
      resource_group_name: rg-prd-ghost
      location: westeurope
      hostingPlanName: furi102-prd-plan
    environment:
      name: prod
    needs: armDeployStaging
    steps:
      - uses: actions/checkout@v2
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy Resource Group ${{ env.resource_group_name }}
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{ env.SUB_ID}}
          region: "${{ env.location }}"
          template: ./arm-templates/resourcegroup.json
          parameters:
            location="${{ env.location }}"
            resourceGroupName=${{ env.resource_group_name }}
          deploymentName: ${{ env.resource_group_name }}
          
      - name: Deploy azure App service
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ env.SUB_ID }}
          resourceGroupName: ${{ env.resource_group_name }}
          template: ./arm-templates/prd-azuredeploy.json
          deploymentMode: complete