name: armTemplateDeployment

on:
  push:
    branches:
      - main

  workflow_dispatch:

env:
  subscriptionId: 33665a07-097d-48db-b1f9-dc30012e19d6
  AZURE_WEBAPP_NAME: "furi102-stg"   # Replace this with your Azure App Service name
  AZURE_WEBAPP_PACKAGE_PATH: '.'   # Replace this with the path to your Node.js app files, if it's not at the root of the repository

jobs:
  armDeployStaging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    env:
      resource_group_name: rg-stg-ghost
      location: westeurope
      hostingPlanName: furi102-str-plan
    environment:
      name: staging

    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Resource Group ${{ env.resource_group_name }}
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{ env.subscriptionId }}
          region: "${{ env.location }}"
          template: ./arm-templates/resourcegroup.json
          parameters:
            location="${{ env.location }}"
            resourceGroupName=${{ env.resource_group_name }}
          deploymentName: ${{ env.resource_group_name }}
          

      - name: Deploy azure App service
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ env.subscriptionId }}
          resourceGroupName: ${{ env.resource_group_name }}
          template: ./arm-templates/stg-azuredeploy.json
          deploymentMode: complete
  build-and-deploy:
    runs-on: ubuntu-latest
    needs: armDeployStaging
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'   # Change this to the Node.js version your app requires

      - name: Install dependencies
        run: npm install ghost-cli@latest -g

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
  armDeploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    env:
      resource_group_name: rg-prd-ghost
      location: westeurope
      hostingPlanName: furi102-prd-plan
    environment:
      name: prod

    needs: armDeployStaging

    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Resource Group ${{ env.resource_group_name }}
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{ env.subscriptionId }}
          region: "${{ env.location }}"
          template: ./arm-templates/resourcegroup.json
          parameters:
            location="${{ env.location }}"
            resourceGroupName=${{ env.resource_group_name }}
          deploymentName: ${{ env.resource_group_name }}
          

      - name: Deploy azure App service
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ env.subscriptionId }}
          resourceGroupName: ${{ env.resource_group_name }}
          template: ./arm-templates/prd-azuredeploy.json
          deploymentMode: complete


