name: armTemplateDeployment

on:
  push:
    branches:
      - main

  workflow_dispatch:

env:
  subscriptionId: 33665a07-097d-48db-b1f9-dc30012e19d6

jobs:
  armDeployStaging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    env:
      resource_group_name: rg-stg-ghost
      location: westeurope
      hostingPlanName: furi102-plan
    environment:
      name: staging

    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Resource Group ${{ env.resource_group_name }}
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{ env.subscriptionId }}
          region: "${{ env.location }}"
          template: ./arm-templates/resourcegroup.json
          parameters:
            location="${{ env.location }}"
            resourceGroupName=${{ env.resource_group_name }}
          deploymentName: ${{ env.resource_group_name }}

      - name: Deploy azure App service
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ env.subscriptionId }}
          resourceGroupName: ${{ env.resource_group_name }}
          template: ./arm-templates/azuredeploy.json
          parameters: 
            hostingPlanName = ${{ hostingPlanName }}
            repoUrl = "https://github.com/furi102/Ghost-Azure"
            branch = main
            sitenName = furi102-site
            siteLocation = westeurope



